#!/bin/bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
#cd "$parent_path"

# 
k=$1
N=$2
M=$(($2/$3))
dim=$4
nb_exp=$5
#  

for sep in "0.5" "0.4" "0.3" "0.2" "0.1" "0.0" "-0.1" "-0.2" "-0.3" "-0.4" "-0.5" "-0.1" "-0.2" "-0.3" "-0.4" "-0.5" ; do
    for ((i=0;i<$nb_exp;i++)); do 
        dataset="generator/${dim}D/${N}N/SEP${sep}/points.csv"
        echo $dataset
        # (
        #     scripts/prog_script_reset
        # ) && clear &&
        # (
        #     gcc -g kmlio_2.c -o program_2 -lm -D _GNU_SOURCE
        # ) && (
            ./program_2 $dataset $k $N $M $dim
        # ) 
    done
done

# printf %s $1 >> $parent_path/../logs/log_iterations.csv 

# generator/10D/13421800N/SEP|/points.csv

#:: generator/\d*D/\d*N/SEP|/points.csv