#!/bin/bash

# vary dmax,M for the given dataset , (sep,N,dim,K)

k=$1
N=$2
dim=$3
MEM_SIZE=$4

# 10 , 8 , 5 , 4 , 2
# 280, 330 , 500 , 610 , 1155

# "-0.6" "-0.5" "-0.4" "-0.3" "-0.2" "-0.1" "0.0" "0.1" "0.2" "0.3" "0.4" "0.5"

for sep in "-0.3" ; do
    for MC in 10 # 33 dmax values
    do 
        scripts/prog_script_cgroup $MEM_SIZE
        for d_max in {300..2400..120}    # 15 dmax values
        do 
            folder="generator/${dim}D/${N}N/SEP${sep}"
            dataset="${folder}/points.csv"
            echo $dataset
            
            M=$(($N/$MC))

            report="SKIP_CHUNKS/reports/${N}N_${M}M_${dim}D_${k}K_${d_max}L"
            echo $report
            
            echo -n "$sep," | tee -a SKIP_CHUNKS/reports/log_skip_chunk.csv

            (
                scripts/prog_script_cache
            ) && (
                gcc -g SKIP_CHUNKS/kmlio_skip_chunk.c -o SKIP_CHUNKS/kmlio_skip_chunk -lm -D _GNU_SOURCE
            ) && (
                SKIP_CHUNKS/kmlio_skip_chunk $dataset $k $N $M $dim $d_max 5
            
            ) && ( ###################

                gcc -g SKIP_CHUNKS/kmlio_eval.c -o SKIP_CHUNKS/kmlio_eval -lm -D _GNU_SOURCE
            ) && (
                SKIP_CHUNKS/kmlio_eval $folder $k $N $M $dim $report
            
            ) && ( ###################

                Rscript generator/cluster_evaluation.R $sep $N $M $k $dim $d_max
            )
             
        done
    done
done

# generator/10D/13421800N/SEP|/points.csv