#!/bin/bash

# vary dmax,M for the given dataset , (sep,N,dim,K)
N=$1
k=$2
dim=$3
nb_exp=$4
kmlio_wcet=1250

# 10 , 8 , 5 , 4 , 2


for sep in "0.0"
do
    mkdir -p SKIP_CHUNKS/reports/SEP${sep}
    for MC in 10          # 33 dmax values
    do 
        python3 ./scripts/prog_mem_script.py $N $MC $k $dim
        for d_max in $kmlio_wcet           #$((kmlio_wcet/4)) $((kmlio_wcet/2)) $kmlio_wcet $((kmlio_wcet*5/4)) $((kmlio_wcet*6/4)) #{..3000..120}    # 10 dmax values
        do
            for ((i=0;i<$nb_exp;i++)); 
            do
                folder="generator/${dim}D/${N}N/SEP${sep}"
                dataset="${folder}/points.csv"
                echo $dataset
                
                M=$(($N/$MC))
                old_loc_report="SKIP_CHUNKS/reports/${N}N_${M}M_${dim}D_${k}K_${d_max}T"
                report="SKIP_CHUNKS/reports/SEP${sep}/${N}N_${M}M_${dim}D_${k}K_${d_max}T_EXP${i}"
                echo $report
                
                echo -n -e "\n$sep," | tee -a SKIP_CHUNKS/reports/log_skip_chunk.csv

                (
                    scripts/prog_script_cache
                ) && 
                (
                    gcc -g SKIP_CHUNKS/kmlio_skip_chunk_fmax.c -o SKIP_CHUNKS/kmlio_skip_chunk -lm -D _GNU_SOURCE
                ) && 
                (
                    cgexec -g cpuset,io,memory:kmeans taskset -c 4 SKIP_CHUNKS/kmlio_skip_chunk $dataset $k $N $M $dim $d_max
                ) && 
                (
                    mv $old_loc_report $report
                ) &&
                # ( ###################

                #     gcc -g SKIP_CHUNKS/kmlio_eval.c -o SKIP_CHUNKS/kmlio_eval -lm -D _GNU_SOURCE
                # ) &&
                #  (
                #     SKIP_CHUNKS/kmlio_eval $folder $k $N $M $dim $report
                
                # ) &&
                # ( ###################

                #     Rscript generator/cluster_evaluation.R $sep $N $M $k $dim $d_max $beta $i
                # ) &&
                (
                    chmod 777 -R .
                ) &&
                (
                    git add .
                ) &&
                (
                    git commit -a -m "execution complete wcet ${N}N ${M}M ${dim}D ${k}K ${d_max}L ${beta}beta EXP${i}"
                )  &&
                (
                    git push
                )
            done
        done
    done
done

