#!/bin/bash

# sep=$6
# for ((i=0;i<$5;i++)); do 
#         (
#             scripts/prog_script_reset
#         ) && (
#             clear && gcc -g kmlio.c -o program -lm -D _GNU_SOURCE
#         ) && (
#             ./program generator/$4D/$2N/SEP$sep/points.csv $1 $2 $(($2/$3)) $4
#         ) 
# done

# 
k=$1
N=$2
M=$(($2/$3))
dim=$4
nb_exp=$5
# 

for sep in  "0.5" "0.4" "0.3" "0.2" "0.1" "0.0" "-0.1" "-0.2" "-0.3" "-0.4" "-0.5" ; do
    for ((i=0;i<$nb_exp;i++)); do 
        dataset="generator/${dim}D/${N}N/SEP${sep}/points.csv"
        echo $dataset
        # (
        #     scripts/prog_script_reset
        # ) && clear &&
        # (
        #     gcc -g kmlio.c -o program -lm -D _GNU_SOURCE
        # ) && (
            ./program $dataset $k $N $M $dim
        # ) 
    done
done

# generator/10D/13421800N/SEP|/points.csv